spring:
  application:
    name: demo-mq
    # Kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: log_group
  # RocketMQ
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: order_group


server:
  port: 12113