spring:
  application:
    name: demo-mq
  # Kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: log_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  # RocketMQ
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: order_group


server:
  port: 12113