spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vector_db
    username: myuser
    password: 525826
  data:
    redis:
      host: localhost
      port: 6379
      password: spjiyou
      timeout: 1000
      lettuce:
        pool:
          max-active: 100
          max-idle: 100
          min-idle: 10